/**
 * src/utils/sandbox_runner.cjs
 * Wraps your friend's logic to run from the project root.
 */
const fs = require("fs");
const path = require("path");
const { execSync, exec } = require("child_process");
const http = require("http");

// CONFIG: files are expected in the ROOT directory where python runs
const INPUT_FILES = ["frontend.json", "backend.json", "docker-compose.json"];
const PROJECT_ROOT = "project_env"; // Renamed to avoid conflicts
const LOG_ROOT = path.join(PROJECT_ROOT, "docker_logs");

// ... (Paste the rest of your friend's utility functions here: ensureDir, processJson, runNpmInstall) ...

// NOTE: For brevity, I assume the rest of the logic (startDocker, getComposeServices, etc.) 
// is exactly as you provided. Just ensure 'PROJECT_ROOT' matches.

// ... (Paste functions: startDocker, getComposeServices, detectFrontendPort, waitForFrontend, openBrowser) ...

function saveLogsAsJson() {
  ensureDir(LOG_ROOT);
  console.log("\nSaving container logs...");

  const services = getComposeServices();
  const output = {};
  const ts = new Date().toISOString().replace(/[:.]/g, "-");

  services.forEach((svc) => {
    try {
      // Added --no-log-prefix for cleaner parsing later
      const logs = execSync(`docker compose logs --no-color --no-log-prefix ${svc}`, {
        cwd: PROJECT_ROOT,
        encoding: "utf-8",
      });
      output[`${svc}`] = logs; // Key is just service name
      console.log(`✓ Saved logs for ${svc}`);
    } catch (err) {
      output[`${svc}`] = `ERROR: ${err.message}`;
    }
  });

  // IMPORTANT: Save to a fixed filename 'latest_logs.json' so Python can find it easily
  const outFile = path.join(LOG_ROOT, "latest_logs.json");
  fs.writeFileSync(outFile, JSON.stringify(output, null, 2));

  console.log("\n✓ Logs saved:", outFile);
  return outFile;
}

async function main() {
  console.log("\n=== 🐳 AI Sandbox Starting ===");
  if (fs.existsSync(PROJECT_ROOT)) {
     // Optional: Clean up previous run? For now, we keep it for speed.
  }
  
  ensureDir(PROJECT_ROOT);

  // 1. Process files generated by Python
  INPUT_FILES.forEach(file => {
      if(fs.existsSync(file)) processJson(file);
  });

  // 2. Install Deps (Frontend/Backend)
  // We assume standard folder names 'frontend' and 'backend' from the JSONs
  if(fs.existsSync(path.join(PROJECT_ROOT, "frontend"))) runNpmInstall("frontend");
  if(fs.existsSync(path.join(PROJECT_ROOT, "backend"))) runNpmInstall("backend");

  // 3. Docker Up
  try {
      startDocker();
  } catch (e) {
      console.error("Docker failed to start:", e.message);
      // We still save logs because maybe the build failed
  }

  // 4. Capture Logs
  saveLogsAsJson();

  // 5. Check Frontend (Optional interaction)
  const port = detectFrontendPort();
  const ready = await waitForFrontend(port, 10000); // 10s timeout for quick check
  
  if (ready) {
      console.log(`\n🚀 Frontend UP at port ${port}`);
  } else {
      console.log(`\n❌ Frontend not reachable after 10s`);
  }
}

main();